# Generated by Django 5.2.9 on 2026-01-22 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_placementcell'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_phonenumber', models.CharField(max_length=100)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.placementcell')),
            ],
        ),
    ]
